name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code from repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Java 17 (Temurin = OpenJDK)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # 3. Run tests
      - name: Run tests
        run: mvn -B test

      # 4. Buid project
      - name: Build with Maven
        run: mvn -B package

      # 5. Package JAR and upload artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: taskflow-api-jar
          path: target/*.jar

